### ISSUE TITLE
Sleigh version error (.sla file has wrong format)

### ISSUE THREAD

**Issue by TheDuchy** [cseagle/blc#10]
Hi, the latest Ghidra I can download from https://ghidra-sre.org/ (9.2.3) Sleigh version in the .sla files is 2, but the one required in this plugin is 3 ([here](https://github.com/cseagle/blc/blob/8b0b7e2995820174eb128ea66713a53a0cd08631/sleighbase.cc#L18)), where can I acquire the newer version?

Platform: `Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64`

**Comment by TheDuchy** [comment]
Oh, I didn't notice that will need to compile Ghidra from source. Mind changing the readme to reflect this?

**Comment by cseagle** [comment]
Please pull and extract the required files from blc_sleigh_files.tgz
