### ISSUE TITLE
ARM Strings not displayed very well

### ISSUE THREAD

**Issue by cfossace** [cseagle/blc#11]
I noticed that ARM strings aren't being displayed very well for arm64 macho files. Here is an example I did with a simple hello world aarch64 Mach-O binary  to show the differences. 

**Example 1: IDA with HEXRAYS decompiler**

<img width="575" alt="Screen Shot 2021-04-20 at 10 23 00 AM" src="https://user-images.githubusercontent.com/8621171/115412691-8d394480-a1c2-11eb-90c5-8c63a531fff1.png">

**Example 2: Ghidra with Ghidra Decompiler**
<img width="189" alt="Screen Shot 2021-04-20 at 10 20 47 AM" src="https://user-images.githubusercontent.com/8621171/115412810-ad690380-a1c2-11eb-8d4d-efef73484306.png">

**Example 3: IDA with blc (Ghidra Decompiler)**
<img width="288" alt="Screen Shot 2021-04-20 at 10 19 54 AM" src="https://user-images.githubusercontent.com/8621171/115412935-ca9dd200-a1c2-11eb-944e-d5f9c1836ab8.png">

For long strings, it would definitely be better (for me) if they were fully displayed in the pseudocode instead of in a shortened variable.

**Comment by cseagle** [comment]
Will you please provide your hello binary so that I may test against it?

**Comment by cfossace** [comment]
Certainly! 

Here is the source as well.  I attached my project a zip here that has the Makefile if you want to generate your own binaries.  If you have a Mac (Intel 64bit) and have run Xcode previously, it should work, but let me know if you run in to any issues. 

(the code is for cross compiling on an intel-based Mac to an ARM binary)


[hello_make.zip](https://github.com/cseagle/blc/files/6352595/hello_make.zip)

**Comment by cseagle** [comment]
Please try the latest version and close or update the issue as necessary

**Comment by cfossace** [comment]
Me and a friend checked it. We are getting this error with IDA 7.5 and 7.6

<img width="653" alt="Screen Shot 2021-04-23 at 3 32 08 PM" src="https://user-images.githubusercontent.com/8621171/115921256-3ee9a700-a449-11eb-9303-0ac2b1b871c5.png">

We tried the prebuilt dylibs and building it ourselves, as well as updating to Ghidra 9.2.3, but it isn't working

I rechecked an old version of it and there was no error
<img width="474" alt="Screen Shot 2021-04-23 at 3 32 16 PM" src="https://user-images.githubusercontent.com/8621171/115921341-59238500-a449-11eb-9f45-6bd971ae3418.png">

**Comment by cseagle** [comment]
Yes, updates to blc generally pull the decompiler from the current git master of Ghidra. They have moved to version 3.0 sla files in master (release is at 2.0 iirc). Have you extracted blc_sleigh_files.tgz into <idadir>/plugins? This is an archive of version 3.0 .sla files that should solve your problem.

**Comment by cfossace** [comment]
I think blc_sleigh_files.tgz is missing from the repo!

**Comment by cseagle** [comment]
Hrm, I see it on GitHub. I'll check again

**Comment by cfossace** [comment]
Oh I do see it! For some reason I thought it would come up in the repo web search but it didn't. It is right there in the main folder though lol. My bad! I'll try the sleigh files out this week. :)

**Comment by cfossace** [comment]
Update: It works and looks amazing! Thanks for doing this so fast. Closing the ticket :) 

<img width="253" alt="Screen Shot 2021-04-28 at 11 45 46 AM" src="https://user-images.githubusercontent.com/8621171/116433284-59d86480-a817-11eb-9175-63734cd70835.png">
