### ISSUE TITLE
Compile issues macOS arm64

### ISSUE THREAD

**Issue by Lichtlos** [cseagle/blc#12]
blc currently does not compile on arm64 macOS:

> make
g++ -c -Wextra -Os -D__MAC__ -D__UNIX__ -D__X64__ -m64  -fPIC -std=c++11 -I../../include/ -I./include/ action.cc -o obj32/action.o
In file included from action.cc:16:
In file included from ./action.hh:21:
In file included from ./block.hh:22:
In file included from ./jumptable.hh:22:
In file included from ./emulateutil.hh:22:
In file included from ./emulate.hh:22:
In file included from ./memstate.hh:22:
In file included from ./pcoderaw.hh:21:
In file included from ./address.hh:29:
In file included from ./space.hh:22:
In file included from ./error.hh:24:
./types.h:223:9: error: unknown type name 'int8'; did you mean 'int'?
typedef int8 intb;              /* This is a signed big integer */
        ^~~~
        int
./types.h:226:9: error: unknown type name 'uint8'
typedef uint8 uintb;            /* This is an unsigned big integer */
        ^

**Comment by cseagle** [comment]
That's actually a problem in Ghidra's types.h file which fails to do any checks for Apple/Arm64 and, as a result, fails to typedef int8.  I'll contemplate how I want to solve that because I prefer not to touch any of the Ghidra files, but may have to in this case until they get it sorted.

**Comment by cseagle** [comment]
Can you please pull and try again. I do not have IDA ARM to link against

**Comment by Lichtlos** [comment]
Unfortunately no difference. Full output:

>  make
g++ -c -Wextra -Os -D__MAC__ -D__UNIX__ -D__X64__ -m64  -fPIC -std=c++11 -I../../include/ -I./include/ action.cc -o obj32/action.o
In file included from action.cc:16:
In file included from ./action.hh:21:
In file included from ./block.hh:22:
In file included from ./jumptable.hh:22:
In file included from ./emulateutil.hh:22:
In file included from ./emulate.hh:22:
In file included from ./memstate.hh:22:
In file included from ./pcoderaw.hh:21:
In file included from ./address.hh:29:
In file included from ./space.hh:22:
In file included from ./error.hh:24:
./types.h:223:9: error: unknown type name 'int8'; did you mean 'int'?
typedef int8 intb;              /* This is a signed big integer */
        ^~~~
        int
./types.h:226:9: error: unknown type name 'uint8'
typedef uint8 uintb;            /* This is an unsigned big integer */
        ^
In file included from action.cc:16:
In file included from ./action.hh:21:
In file included from ./block.hh:22:
In file included from ./jumptable.hh:22:
In file included from ./emulateutil.hh:22:
In file included from ./emulate.hh:22:
In file included from ./memstate.hh:22:
In file included from ./pcoderaw.hh:21:
In file included from ./address.hh:29:
In file included from ./space.hh:23:
./xml.hh:52:3: error: unknown type name 'int4'
  int4 getLength(void) const { return name.size(); }            ///< Get the number of attributes associated wit...
  ^
./xml.hh:53:24: error: unknown type name 'int4'
  const string &getURI(int4 i) const { return bogus_uri; }      ///< Get the namespace URI associated with the i...
                       ^
./xml.hh:54:30: error: unknown type name 'int4'
  const string &getLocalName(int4 i) const { return *name[i]; } ///< Get the local name of the i-th attribute
                             ^
./xml.hh:55:26: error: unknown type name 'int4'
  const string &getQName(int4 i) const { return *name[i]; }     ///< Get the qualified name of the i-th attribute
                         ^
./xml.hh:61:26: error: unknown type name 'int4'
  const string &getValue(int4 i) const { return *value[i]; }    ///< Get the value of the i-th attribute
                         ^
./xml.hh:45:9: error: unknown type name 'uint4'; did you mean 'uint'?
    for(uint4 i=0;i<name.size();++i) { delete name[i]; delete value[i]; }
        ^~~~~
        uint
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/types.h:92:33: note:
      'uint' declared here
typedef unsigned int            uint;           /* Sys V compatibility */
                                ^
In file included from action.cc:16:
In file included from ./action.hh:21:
In file included from ./block.hh:22:
In file included from ./jumptable.hh:22:
In file included from ./emulateutil.hh:22:
In file included from ./emulate.hh:22:
In file included from ./memstate.hh:22:
In file included from ./pcoderaw.hh:21:
In file included from ./address.hh:29:
In file included from ./space.hh:23:
./xml.hh:65:9: error: unknown type name 'uint4'; did you mean 'uint'?
    for(uint4 i=0;i<name.size();++i)
        ^~~~~
        uint
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/types.h:92:33: note:
      'uint' declared here
typedef unsigned int            uint;           /* Sys V compatibility */
                                ^
In file included from action.cc:16:
In file included from ./action.hh:21:
In file included from ./block.hh:22:
In file included from ./jumptable.hh:22:
In file included from ./emulateutil.hh:22:
In file included from ./emulate.hh:22:
In file included from ./memstate.hh:22:
In file included from ./pcoderaw.hh:21:
In file included from ./address.hh:29:
In file included from ./space.hh:23:
./xml.hh:108:44: error: unknown type name 'int4'
  virtual void characters(const char *text,int4 start,int4 length)=0;
                                           ^
./xml.hh:108:55: error: unknown type name 'int4'
  virtual void characters(const char *text,int4 start,int4 length)=0;
                                                      ^
./xml.hh:115:53: error: unknown type name 'int4'
  virtual void ignorableWhitespace(const char *text,int4 start,int4 length)=0;
                                                    ^
./xml.hh:115:64: error: unknown type name 'int4'
  virtual void ignorableWhitespace(const char *text,int4 start,int4 length)=0;
                                                               ^
./xml.hh:168:35: error: unknown type name 'int4'
  void addContent(const char *str,int4 start,int4 length) {
                                  ^
./xml.hh:168:46: error: unknown type name 'int4'
  void addContent(const char *str,int4 start,int4 length) {
                                             ^
./xml.hh:197:3: error: unknown type name 'int4'
  int4 getNumAttributes(void) const { return attr.size(); }     ///< Get the number of attributes for \b this element
  ^
./xml.hh:198:34: error: unknown type name 'int4'
  const string &getAttributeName(int4 i) const { return attr[i]; }      ///< Get the name of the i-th attribute
                                 ^
./xml.hh:199:35: error: unknown type name 'int4'
  const string &getAttributeValue(int4 i) const { return value[i]; }    ///< Get the value of the i-th attribute
                                  ^
./xml.hh:233:44: error: unknown type name 'int4'
  virtual void characters(const char *text,int4 start,int4 length);
                                           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [obj32/action.o] Error 1

**Comment by Lichtlos** [comment]
Was too tired at first. But fixing the logic in the define statement helped:
https://github.com/cseagle/blc/pull/13

Thanks for the help :)

**Comment by cseagle** [comment]
Thanks, I messed up that edit in any case, the || should have been down at __APPLE_CC__, but it looks like the Ghidra repo has an updated types.h that appears to support Apple/AARCH. If that fails. Please let me know if the latest version works

**Comment by Lichtlos** [comment]
This compiles and works as intended now.

**Comment by Lichtlos** [comment]
In case someone needs the precompiled bins for 32bit & 64bit:
[blc_blc64.dylib_apple_arm64.zip](https://github.com/cseagle/blc/files/6369564/blc_blc64.dylib_apple_arm64.zip)

**Comment by cseagle** [comment]
Thanks!
