### ISSUE TITLE
DOS 16bit architecture supported? 

### ISSUE THREAD

**Issue by palmerj** [cseagle/blc#16]
The plugin didn't seems to load and saw this in the console

```
Using sleigh id: x86:LE:16:Real Mode:windows
Bad symbol xml
Could not create architecture
```

I've copied the sleigh processors into plugins/Ghidra/Processors from 10.2.2. 

The file I'm using is s DOS 16bit real mode EXE https://gist.github.com/palmerj/d006c9abf0eaf1be085ccf8f734359e1

**Comment by cseagle** [comment]
This works fine for me with the latest version of the plugin and IDA8.1. I suspect that if you are still using an older 7.5 version of the plugin that the newer sleigh files are incompatible. I'll leave this open until I have a chance to try to build for 7.5. In the meantime, sleigh files from an older version of Ghidra (late 9.x perhaps?) may help you get things loaded.

**Comment by palmerj** [comment]
OK thanks I will give it a try. A new build would be great, cause I see you fixed stuff for parameter renaming. Maybe I should consider upgrading, but I don't think much has changed for DOS 16bit exes in newer versions.

**Comment by palmerj** [comment]
Updated to 9.2.4 processors SLA files and got:

Using sleigh id: x86:LE:16:Real Mode:windows
.sla file has wrong format
Could not create architecture

**Comment by palmerj** [comment]
Just tired 9.0.1 and same result

**Comment by palmerj** [comment]
Problem solved with the new binaries. This can be closed.
