### ISSUE TITLE
Crash after renaming local var

### ISSUE THREAD

**Issue by patois** [cseagle/blc#4]
Hi,

I haven't had the chance to debug this issue yet but I found it to be reproducible:

1. Decompile a function that references/calls another function
2. Rename one of its local variables so that it contains an underscore character ("test_123")
3. Double click the symbol/name of a function that is the called by the decompiled function

-> Crash

**Comment by cseagle** [comment]
Thanks. I could reproduce. Source fix is in git. Will push new binaries when they finish building. Please comment if still broken or close if it works for you.

**Comment by patois** [comment]
Excellent! That fixes it, thank you very much!
