### ISSUE TITLE
Compile fixes for 7.6

### ISSUE THREAD

**Issue by vanhauser-thc** [cseagle/blc#9]
To compile in my Linux IDA Pro 7.6 the following changes were necessary:
```
diff --git a/Makefile b/Makefile
index 70ccacb..4a3968b 100644
--- a/Makefile
+++ b/Makefile
@@ -11,7 +11,7 @@ PLATFORM=$(shell uname | cut -f 1 -d _)
 PROC=blc
 
 ifeq "$(PLATFORM)" "Linux"
-IDA=/opt/ida-$(IDAVER)
+IDA=/opt/idapro-$(IDAVER)
 HAVE_IDA64=$(shell if [ -f $(IDA)/libida64.so ]; then echo -n yes; fi)
 PLATFORM_CFLAGS=-D__LINUX__ -D__UNIX__
 PLATFORM_LDFLAGS=-shared -s
diff --git a/plugin.cc b/plugin.cc
index 7245f51..d85a1d0 100644
--- a/plugin.cc
+++ b/plugin.cc
@@ -671,7 +671,7 @@ bool get_sleigh_id(string &sleigh) {
          break;
       case PLFM_386:
          //options include "System Management Mode" "Real Mode" "Protected Mode" "default"
-         sleigh += is_64 ? ":64" : (inf_is_32bit() ? ":32" : ":16");
+         sleigh += is_64 ? ":64" : (!inf_is_16bit() ? ":32" : ":16");
          if (sleigh.find(":16") != string::npos) {
             sleigh += ":Real Mode";
          }
```
dunno if this works for older versions too and if ida home is using just /opt/ida-VER, so not doing a pull request.
inf_is_32bit does not exist anymore it is now either inf_is_32bit_or_higher or inf_is_32bit_exactly.

**Comment by cseagle** [comment]
I think I have incorporated these changes or addressed the issues in alternative ways, If you find that things compile and work for you do you mind closing the issue?

**Comment by vanhauser-thc** [comment]
it compiles now fine :)

one thing that would be nice: `make install` - as the ida install path is already known in the Makefile, that would be the intuitive way

**Comment by cseagle** [comment]
Added an install target
